apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-worker-audits"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-worker-audits"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-worker-audits"
    spec:
      initContainers:
      {{- include "redisCheck" $ | nindent 6 }}
      {{- include "dbCheck" $ | nindent 6 }}
      containers:
      - name: appwrite-worker-audits
        image: "appwrite/appwrite:{{ .Chart.AppVersion }}"
        command:
          - "worker-audits"
        imagePullPolicy: IfNotPresent
        env:
          - name: _APP_ENV
            valueFrom:
              configMapKeyRef:
                name: "{{ .Release.Name }}-env"
                key: _APP_ENV
          - name: _APP_SMS_PROVIDER
            valueFrom:
              configMapKeyRef:
                name: "{{ .Release.Name }}-env"
                key: _APP_SMS_PROVIDER
          - name: _APP_SMS_FROM
            valueFrom:
              configMapKeyRef:
                name: "{{ .Release.Name }}-env"
                key: _APP_SMS_FROM
          - name: _APP_LOGGING_PROVIDER
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-env"
                key: _APP_LOGGING_PROVIDER
          - name: _APP_LOGGING_CONFIG
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-env"
                key: _APP_LOGGING_CONFIG
          {{- include "redisEnv" $ | nindent 10 }}

