apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-worker-webhooks"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-worker-webhooks"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-worker-webhooks"
    spec:
      initContainers:
      {{- include "redisCheck" $ | nindent 6 }}
      {{- include "dbCheck" $ | nindent 6 }}
      containers:
      - name: appwrite-worker-webhooks
        image: "appwrite/appwrite:{{ .Chart.AppVersion }}"
        command:
          - "worker-webhooks"
        imagePullPolicy: IfNotPresent
        env:
          - name: _APP_ENV
            valueFrom:
              configMapKeyRef:
                name: "{{ .Release.Name }}-env"
                key: _APP_ENV
          - name: _APP_SYSTEM_SECURITY_EMAIL_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: "{{ .Release.Name }}-env"
                key: _APP_SYSTEM_SECURITY_EMAIL_ADDRESS
          {{- include "redisEnv" $ | nindent 10 }}
