{{- with .Values.volumes.appwrite.cache }}
{{- if (and .enabled .create) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .pvcName }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .storageRequest }}
  storageClassName: {{ .storageClass }}
{{- end -}}
{{- end -}}