apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-influxdb"
spec:
  ports:
    - port: {{ .Values.influxdb.port }}
      targetPort: {{ .Values.influxdb.port }}
  selector:
    app: "{{ .Release.Name }}-influxdb"