{{- if .Values.ingress.realtime.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realtime
  labels:
    app: realtime
  annotations:
    {{- .Values.ingress.realtime.annotations | toYaml | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.appwrite.domain }}
      http:
        paths:
          - path: /v1/realtime
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-realtime"
                port:
                  number: 80
  {{- if .Values.ingress.realtime.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.appwrite.domain | quote }}
      secretName: {{ .Values.ingress.realtime.tls.secretName }}
  {{- end -}}
{{- end -}}