kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-env"
data:
  _APP_ENV: {{ .Values.appwrite.env | quote }}
  _APP_LOCALE: {{ .Values.appwrite.locale | quote }}
  _APP_OPTIONS_ABUSE: {{ include "boolToStr" .Values.appwrite.options.abuse }}
  _APP_OPTIONS_FORCE_HTTPS: {{ include "boolToStr" .Values.appwrite.options.forceHttps }}
  _APP_DOMAIN: {{ .Values.appwrite.domain | quote }}
  _APP_DOMAIN_TARGET: {{ .Values.appwrite.domain | quote }}
  _APP_CONSOLE_WHITELIST_ROOT: {{ include "boolToStr" .Values.appwrite.console.whitelist.root }}
  _APP_CONSOLE_WHITELIST_EMAILS: {{ include "array.join" .Values.appwrite.console.whitelist.emails }}
  _APP_CONSOLE_WHITELIST_IPS: {{ include "array.join" .Values.appwrite.console.whitelist.ips }}
  _APP_SYSTEM_EMAIL_NAME: {{ .Values.appwrite.system.email.name | quote }}
  _APP_SYSTEM_EMAIL_ADDRESS: {{ .Values.appwrite.system.email.addr | quote }}
  _APP_SYSTEM_RESPONSE_FORMAT: {{ .Values.appwrite.system.responseFormat | quote }}
  _APP_SYSTEM_SECURITY_EMAIL_ADDRESS: {{ .Values.appwrite.system.securityAddress | quote }}
  _APP_USAGE_STATS: {{ include "boolToStr" .Values.appwrite.usageStats }}
  _APP_REDIS_PORT: {{ .Values.redis.port | quote }}
  _APP_DB_PORT: {{ .Values.db.port | quote }}
  _APP_DB_SCHEMA: {{ .Values.db.schema | quote }}
  _APP_INFLUXDB_PORT: {{ .Values.influxdb.port | quote }}
  _APP_STATSD_PORT: {{ .Values.statsd.port | quote }}
  _APP_SMTP_HOST: {{ .Values.smtp.host | quote }}
  _APP_SMTP_PORT: {{ .Values.smtp.port | quote }}
  _APP_SMTP_SECURE: {{ .Values.smtp.secure | quote }}
  _APP_STORAGE_LIMIT: {{ include "si.toNum" .Values.storage.limit }}
  _APP_STORAGE_ANTIVIRUS: {{ include "boolToStr" .Values.storage.antivirus.enabled }}
  _APP_STORAGE_ANTIVIRUS_HOST: {{ .Values.storage.antivirus.host | quote }}
  _APP_STORAGE_ANTIVIRUS_PORT: {{ .Values.storage.antivirus.port | quote }}
  _APP_FUNCTIONS_TIMEOUT: {{ .Values.functions.timeout | quote }}
  _APP_FUNCTIONS_CONTAINERS: {{ .Values.functions.containers | quote }}
  _APP_FUNCTIONS_CPUS: {{ .Values.functions.cpus | quote }}
  _APP_FUNCTIONS_MEMORY: {{ .Values.functions.memory | quote }}
  _APP_FUNCTIONS_MEMORY_SWAP: {{ .Values.functions.swap | quote }}
  _APP_FUNCTIONS_RUNTIMES: {{ include "array.join" .Values.functions.runtimes }}
  _APP_FUNCTIONS_ENVS: {{ include "array.join" .Values.functions.envs }}