apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-env"
type: Opaque
data:
  _APP_OPENSSL_KEY_V1: {{ .Values.appwrite.sslKey | b64enc }}
  {{ if ne .Values.redis.user "" -}}_APP_REDIS_USER: {{ .Values.redis.user | b64enc }}{{- end -}}
  {{ if ne .Values.redis.pass "" -}}_APP_REDIS_PASS: {{ .Values.redis.pass | b64enc }}{{- end -}}
  _APP_DB_USER: {{ .Values.db.user | b64enc }}
  _APP_DB_PASS: {{ .Values.db.password | b64enc }}
  _APP_DB_ROOT_PASS: {{ .Values.db.rootPass | b64enc }}
  _APP_SMTP_USERNAME: {{ .Values.smtp.user | b64enc }}
  _APP_SMTP_PASSWORD: {{ .Values.smtp.pass | b64enc }}